# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coordinator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Then', '~> 3.0'
  pod 'SnapKit', '~> 5.6'
  # Pods for Coordinator

end
